namespace ImageGenerator.MAUI.Core.Domain.Entities;

/// <summary>
/// Represents an image generated by the system, including any associated metadata.
/// </summary>
public class GeneratedImage
{
    public string? Message { get; set; }
    public byte[]? ImageData { get; set; }
}