namespace ImageGenerator.MAUI.Core.Domain.Entities;

/// <summary>
/// Represents an image generated by the system, including any associated metadata.
/// </summary>
public class GeneratedImage
{
    /// Gets or sets the message indicating the status or result of the image generation process.
    /// This property typically contains information such as success confirmation or error details.
    public string? Message { get; set; }

    /// <summary>
    /// Gets or sets the file path of the generated image.
    /// This property may store the local file system path where the generated image
    /// is saved after processing by the relevant image generation service.
    /// It can be null if the file path is not available or the image is not saved to disk.
    /// </summary>
    public string? FilePath { get; set; }

    /// <summary>
    /// Represents the Base64-encoded image data generated by the system.
    /// </summary>
    /// <remarks>
    /// This property contains the image data encoded as a Base64 string, which can be utilized
    /// to display or manipulate the image in scenarios where direct file system storage is
    /// not preferred. If the image generation process fails, this property may contain a null value.
    /// </remarks>
    public string? ImageDataBase64 { get; set; } // now safe across ABI
}